name: tests

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m unittest test_my_utils.py    
    
  run_func_tests:
    defaults:
      run:
        shell: bash -el {0}  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
      - run: |
            conda activate swe4s
            bash test/func/test_print_fires.sh  
    
  run_style_check:
    defaults:
      run:
        shell: bash -el {0} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
      - run: |
          conda activate swe4s
          pycodestyle $(git ls-files "*.py")
