<<<<<<< HEAD
on: 
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
=======
on: push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
>>>>>>> d500aedecb43fab8e3e2505d7d64216b1b74d7bd

jobs:
    run_unit_tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
    - run: |
        cd test/unit
        python -m unittest test_my_utils.py    
    
 run_func_tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
    - run: |
        bash test/func/test_print_fires.sh     