name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd test/unit
          python -m unittest test_my_utils.py

  run_func_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run functional tests
        run: |
          bash test/func/test_print_fires.sh

  run_style_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pycodestyle
        run: |
          pip install pycodestyle
      - name: Run style check
        run: |
          pycodestyle $(git ls-files "*.py")
