name: tests

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd test/unit
          python -m unittest test_my_utils.py    
    
  run_func_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}  
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          activate-environment: swe4s
      - run: |
          bash test/func/test_print_fires.sh    
    
  run_style_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}  
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          activate-environment: swe4s
      - run: |
          pycodestyle $(git ls-files "*.py")

          